//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReporteActividades
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class DetalleIndividual
    {
        public int ID { get; set; }
        public string DESAXX { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Sistema { get; set; }
        public string TipoActividad { get; set; }
        public string DetalleActividad { get; set; }
        public int HorasDedicadas { get; set; }
        public string PorcentajeAvance { get; set; }
    }
}
